a = ("CIMultiDictProxy("
     "'Date': 'Sun, 09 Nov 2025 08:22:22 GMT',"
     "'Content-Type': 'application/json; charset=utf-8',"
     "'Transfer-Encoding': 'chunked',"
     "'Connection': 'keep-alive',"
     "'CF-RAY': '99bbe6e3de43eefa-CMH',"
     "'x-powered-by': 'Express',"
     "'Vary': 'Origin, Accept-Encoding',"
     "'Access-Control-Allow-Credentials': 'true',"
     "'Cache-Control': 'no-store',"
     "'Etag': 'W/'c8-/wUFn2jBuQ1ByCc0hEsJiVmDFvg' 'x-envoy-upstream-service-time': '38',"
     "'Content-Encoding': 'gzip',"
     "'x-envoy-decorator-operation': 'client-graphql-ou-client',"
     "'cf-cache-status': 'DYNAMIC',"
     "'Set-Cookie': '__cf_bm=.x4kR5.JahaOyNXxvbz2yF.aOqolsD6J8eHuNkuopSE-1762676542-1.0.1.1-HbXJNGrzsAYA2RBPaLU.Xh2kXNAhLo2o6P_groOF3kvawm748_Fn6DlbjOvujul7TuJl4Bo_w35sw84WgJibsDrPEcjyh6hQkB.QWbOOS4k; path=/; expires=Sun, 09-Nov-25 08:52:22 GMT; domain=.offerup.com; HttpOnly; Secure; SameSite=None',"
     "'Report-To': '{'ndpoints'[{'rl''ttps:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=lhVeumMn%2BTOpfiGrIDu%2Fcc%2BSpbrvTWYe4Mip4e0mQFlCEy6EEBRvadJaHzzwj7CDJCXngPUz%2BmnW9NsY5RLCCl41uHROSlohDevfi9fmqLolUxNnVx9jkJWOJi1d40jDj%2FKiLbxILPB9EtU9'],'roup''f-nel''ax_age'604800}',"
     "'NEL': '{'uccess_fraction'0,'eport_to''f-nel''ax_age'604800}',"
     "'Strict-Transport-Security': 'max-age=2592000',"
     "'expect-ct': 'max-age=86400, enforce',"
     "'referrer-policy': 'same-origin',"
     "'x-content-type-options': 'nosniff',"
     "'x-frame-options': 'SAMEORIGIN',"
     "'x-xss-protection': '1; mode=block',"
     "'Server': 'cloudflare')>")